# env:
#   HOST=http://159.203.50.162/
#   TOKEN=792e11cc29fb411439bf
#   T_MAX=50
#   T_MIN=20
#   DATABASE_URL=157.230.69.113
#   HUB_CONNECTION=None
#   TICKETS=10
#   DATABASE_URL=postgresql://user02eq3:ulurS8q1utgQ3jYR@157.230.69.113:5432/db02eq3
## To implement
repos:
- repo: local
  hooks:
    - id: pylint
      name: pylint
      entry: pylint
      language: system
      types: [python]
      args:
        [
          "-rn", # Only display messages
          "-sn", # Don't display the score
        ]
    - id: black
      name: black
      entry: black
      language: system
      types: [python]
    - id: unittests
      name: run unit tests
      entry: python -m unittest
      language: system
      pass_filenames: false
      args: ["discover"]
