name: Python CI/CD with Docker

on:
  push:
    paths:
      - '*'
      - '**/*'  # Trigger on changes in all subdirectories only if there is a change
    branches:
      - ci_cd_pipeline_docker
      - main
      - S.Data_2

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: python -m unittest


  push:
    runs-on: ubuntu-latest

    needs: test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to DockerHub
        uses: docker/login-action@v1
        with:
          username: thameur.aissaoui@gmail.com
          password: Canada2018!

      - name: Build and Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: thaais1/oxygen-cs-grp2-eq3:latest

      # Add Kubernetes deployment step
      - name: Deploy to Kubernetes
        uses: appleboy/kubectl-action@v0.1.5
        with:
          args: apply -f hvac-deploy.yaml















