name: Python CI/CD with Docker

on:
  push:
    branches:
      - ci_cd_pipeline_docker
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

  push:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t thaais1/oxygen-cs-grp2-eq3:latest .
        working-directory: ${{ github.workspace }}

      - name: Log in to Docker Hub
        run: docker login -u thameur.aissaoui@gmail.com -p Canada2018!

      - name: Push Docker image to Docker Hub
        run: docker push thaais1/oxygen-cs-grp2-eq3:latest
        working-directory: ${{ github.workspace }}


